# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adminz/桌面/project/HighPerformanceServer/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adminz/桌面/project/HighPerformanceServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adminz/桌面/project/HighPerformanceServer/CMakeFiles /home/adminz/桌面/project/HighPerformanceServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adminz/桌面/project/HighPerformanceServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_uri

# Build rule for target.
test_uri: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_uri
.PHONY : test_uri

# fast build rule for target.
test_uri/fast:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/build
.PHONY : test_uri/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_server

# Build rule for target.
test_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_server
.PHONY : test_server

# fast build rule for target.
test_server/fast:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/build
.PHONY : test_server/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named test_tcpserver

# Build rule for target.
test_tcpserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcpserver
.PHONY : test_tcpserver

# fast build rule for target.
test_tcpserver/fast:
	$(MAKE) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/build
.PHONY : test_tcpserver/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

address.o: address.cpp.o

.PHONY : address.o

# target to build an object file
address.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/address.cpp.o
.PHONY : address.cpp.o

address.i: address.cpp.i

.PHONY : address.i

# target to preprocess a source file
address.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/address.cpp.i
.PHONY : address.cpp.i

address.s: address.cpp.s

.PHONY : address.s

# target to generate assembly for a file
address.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/address.cpp.s
.PHONY : address.cpp.s

bytearray.o: bytearray.cpp.o

.PHONY : bytearray.o

# target to build an object file
bytearray.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/bytearray.cpp.o
.PHONY : bytearray.cpp.o

bytearray.i: bytearray.cpp.i

.PHONY : bytearray.i

# target to preprocess a source file
bytearray.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/bytearray.cpp.i
.PHONY : bytearray.cpp.i

bytearray.s: bytearray.cpp.s

.PHONY : bytearray.s

# target to generate assembly for a file
bytearray.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/bytearray.cpp.s
.PHONY : bytearray.cpp.s

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/config.cpp.s
.PHONY : config.cpp.s

example/echo_server.o: example/echo_server.cpp.o

.PHONY : example/echo_server.o

# target to build an object file
example/echo_server.cpp.o:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cpp.o
.PHONY : example/echo_server.cpp.o

example/echo_server.i: example/echo_server.cpp.i

.PHONY : example/echo_server.i

# target to preprocess a source file
example/echo_server.cpp.i:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cpp.i
.PHONY : example/echo_server.cpp.i

example/echo_server.s: example/echo_server.cpp.s

.PHONY : example/echo_server.s

# target to generate assembly for a file
example/echo_server.cpp.s:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cpp.s
.PHONY : example/echo_server.cpp.s

fd_manager.o: fd_manager.cpp.o

.PHONY : fd_manager.o

# target to build an object file
fd_manager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/fd_manager.cpp.o
.PHONY : fd_manager.cpp.o

fd_manager.i: fd_manager.cpp.i

.PHONY : fd_manager.i

# target to preprocess a source file
fd_manager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/fd_manager.cpp.i
.PHONY : fd_manager.cpp.i

fd_manager.s: fd_manager.cpp.s

.PHONY : fd_manager.s

# target to generate assembly for a file
fd_manager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/fd_manager.cpp.s
.PHONY : fd_manager.cpp.s

fiber.o: fiber.cpp.o

.PHONY : fiber.o

# target to build an object file
fiber.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/fiber.cpp.o
.PHONY : fiber.cpp.o

fiber.i: fiber.cpp.i

.PHONY : fiber.i

# target to preprocess a source file
fiber.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/fiber.cpp.i
.PHONY : fiber.cpp.i

fiber.s: fiber.cpp.s

.PHONY : fiber.s

# target to generate assembly for a file
fiber.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/fiber.cpp.s
.PHONY : fiber.cpp.s

hook.o: hook.cpp.o

.PHONY : hook.o

# target to build an object file
hook.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/hook.cpp.o
.PHONY : hook.cpp.o

hook.i: hook.cpp.i

.PHONY : hook.i

# target to preprocess a source file
hook.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/hook.cpp.i
.PHONY : hook.cpp.i

hook.s: hook.cpp.s

.PHONY : hook.s

# target to generate assembly for a file
hook.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/hook.cpp.s
.PHONY : hook.cpp.s

http/http.o: http/http.cpp.o

.PHONY : http/http.o

# target to build an object file
http/http.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http.cpp.o
.PHONY : http/http.cpp.o

http/http.i: http/http.cpp.i

.PHONY : http/http.i

# target to preprocess a source file
http/http.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http.cpp.i
.PHONY : http/http.cpp.i

http/http.s: http/http.cpp.s

.PHONY : http/http.s

# target to generate assembly for a file
http/http.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http.cpp.s
.PHONY : http/http.cpp.s

http/http11_parser_rl.o: http/http11_parser_rl.cpp.o

.PHONY : http/http11_parser_rl.o

# target to build an object file
http/http11_parser_rl.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http11_parser_rl.cpp.o
.PHONY : http/http11_parser_rl.cpp.o

http/http11_parser_rl.i: http/http11_parser_rl.cpp.i

.PHONY : http/http11_parser_rl.i

# target to preprocess a source file
http/http11_parser_rl.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http11_parser_rl.cpp.i
.PHONY : http/http11_parser_rl.cpp.i

http/http11_parser_rl.s: http/http11_parser_rl.cpp.s

.PHONY : http/http11_parser_rl.s

# target to generate assembly for a file
http/http11_parser_rl.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http11_parser_rl.cpp.s
.PHONY : http/http11_parser_rl.cpp.s

http/http_connection.o: http/http_connection.cpp.o

.PHONY : http/http_connection.o

# target to build an object file
http/http_connection.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_connection.cpp.o
.PHONY : http/http_connection.cpp.o

http/http_connection.i: http/http_connection.cpp.i

.PHONY : http/http_connection.i

# target to preprocess a source file
http/http_connection.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_connection.cpp.i
.PHONY : http/http_connection.cpp.i

http/http_connection.s: http/http_connection.cpp.s

.PHONY : http/http_connection.s

# target to generate assembly for a file
http/http_connection.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_connection.cpp.s
.PHONY : http/http_connection.cpp.s

http/http_parser.o: http/http_parser.cpp.o

.PHONY : http/http_parser.o

# target to build an object file
http/http_parser.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_parser.cpp.o
.PHONY : http/http_parser.cpp.o

http/http_parser.i: http/http_parser.cpp.i

.PHONY : http/http_parser.i

# target to preprocess a source file
http/http_parser.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_parser.cpp.i
.PHONY : http/http_parser.cpp.i

http/http_parser.s: http/http_parser.cpp.s

.PHONY : http/http_parser.s

# target to generate assembly for a file
http/http_parser.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_parser.cpp.s
.PHONY : http/http_parser.cpp.s

http/http_server.o: http/http_server.cpp.o

.PHONY : http/http_server.o

# target to build an object file
http/http_server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_server.cpp.o
.PHONY : http/http_server.cpp.o

http/http_server.i: http/http_server.cpp.i

.PHONY : http/http_server.i

# target to preprocess a source file
http/http_server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_server.cpp.i
.PHONY : http/http_server.cpp.i

http/http_server.s: http/http_server.cpp.s

.PHONY : http/http_server.s

# target to generate assembly for a file
http/http_server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/http_server.cpp.s
.PHONY : http/http_server.cpp.s

http/httpclient_parser_rl.o: http/httpclient_parser_rl.cpp.o

.PHONY : http/httpclient_parser_rl.o

# target to build an object file
http/httpclient_parser_rl.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/httpclient_parser_rl.cpp.o
.PHONY : http/httpclient_parser_rl.cpp.o

http/httpclient_parser_rl.i: http/httpclient_parser_rl.cpp.i

.PHONY : http/httpclient_parser_rl.i

# target to preprocess a source file
http/httpclient_parser_rl.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/httpclient_parser_rl.cpp.i
.PHONY : http/httpclient_parser_rl.cpp.i

http/httpclient_parser_rl.s: http/httpclient_parser_rl.cpp.s

.PHONY : http/httpclient_parser_rl.s

# target to generate assembly for a file
http/httpclient_parser_rl.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/httpclient_parser_rl.cpp.s
.PHONY : http/httpclient_parser_rl.cpp.s

http/httpsession.o: http/httpsession.cpp.o

.PHONY : http/httpsession.o

# target to build an object file
http/httpsession.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/httpsession.cpp.o
.PHONY : http/httpsession.cpp.o

http/httpsession.i: http/httpsession.cpp.i

.PHONY : http/httpsession.i

# target to preprocess a source file
http/httpsession.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/httpsession.cpp.i
.PHONY : http/httpsession.cpp.i

http/httpsession.s: http/httpsession.cpp.s

.PHONY : http/httpsession.s

# target to generate assembly for a file
http/httpsession.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/httpsession.cpp.s
.PHONY : http/httpsession.cpp.s

http/servlet.o: http/servlet.cpp.o

.PHONY : http/servlet.o

# target to build an object file
http/servlet.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/servlet.cpp.o
.PHONY : http/servlet.cpp.o

http/servlet.i: http/servlet.cpp.i

.PHONY : http/servlet.i

# target to preprocess a source file
http/servlet.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/servlet.cpp.i
.PHONY : http/servlet.cpp.i

http/servlet.s: http/servlet.cpp.s

.PHONY : http/servlet.s

# target to generate assembly for a file
http/servlet.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http/servlet.cpp.s
.PHONY : http/servlet.cpp.s

iomanager.o: iomanager.cpp.o

.PHONY : iomanager.o

# target to build an object file
iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/iomanager.cpp.o
.PHONY : iomanager.cpp.o

iomanager.i: iomanager.cpp.i

.PHONY : iomanager.i

# target to preprocess a source file
iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/iomanager.cpp.i
.PHONY : iomanager.cpp.i

iomanager.s: iomanager.cpp.s

.PHONY : iomanager.s

# target to generate assembly for a file
iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/iomanager.cpp.s
.PHONY : iomanager.cpp.s

log.o: log.cpp.o

.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i

.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s

.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log.cpp.s
.PHONY : log.cpp.s

scheduler.o: scheduler.cpp.o

.PHONY : scheduler.o

# target to build an object file
scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/scheduler.cpp.o
.PHONY : scheduler.cpp.o

scheduler.i: scheduler.cpp.i

.PHONY : scheduler.i

# target to preprocess a source file
scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/scheduler.cpp.i
.PHONY : scheduler.cpp.i

scheduler.s: scheduler.cpp.s

.PHONY : scheduler.s

# target to generate assembly for a file
scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/scheduler.cpp.s
.PHONY : scheduler.cpp.s

socket.o: socket.cpp.o

.PHONY : socket.o

# target to build an object file
socket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socket.cpp.o
.PHONY : socket.cpp.o

socket.i: socket.cpp.i

.PHONY : socket.i

# target to preprocess a source file
socket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socket.cpp.i
.PHONY : socket.cpp.i

socket.s: socket.cpp.s

.PHONY : socket.s

# target to generate assembly for a file
socket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socket.cpp.s
.PHONY : socket.cpp.s

socketstream.o: socketstream.cpp.o

.PHONY : socketstream.o

# target to build an object file
socketstream.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socketstream.cpp.o
.PHONY : socketstream.cpp.o

socketstream.i: socketstream.cpp.i

.PHONY : socketstream.i

# target to preprocess a source file
socketstream.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socketstream.cpp.i
.PHONY : socketstream.cpp.i

socketstream.s: socketstream.cpp.s

.PHONY : socketstream.s

# target to generate assembly for a file
socketstream.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socketstream.cpp.s
.PHONY : socketstream.cpp.s

stream.o: stream.cpp.o

.PHONY : stream.o

# target to build an object file
stream.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/stream.cpp.o
.PHONY : stream.cpp.o

stream.i: stream.cpp.i

.PHONY : stream.i

# target to preprocess a source file
stream.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/stream.cpp.i
.PHONY : stream.cpp.i

stream.s: stream.cpp.s

.PHONY : stream.s

# target to generate assembly for a file
stream.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/stream.cpp.s
.PHONY : stream.cpp.s

tcp_server.o: tcp_server.cpp.o

.PHONY : tcp_server.o

# target to build an object file
tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tcp_server.cpp.o
.PHONY : tcp_server.cpp.o

tcp_server.i: tcp_server.cpp.i

.PHONY : tcp_server.i

# target to preprocess a source file
tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tcp_server.cpp.i
.PHONY : tcp_server.cpp.i

tcp_server.s: tcp_server.cpp.s

.PHONY : tcp_server.s

# target to generate assembly for a file
tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tcp_server.cpp.s
.PHONY : tcp_server.cpp.s

tests/mytest.o: tests/mytest.cpp.o

.PHONY : tests/mytest.o

# target to build an object file
tests/mytest.cpp.o:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/tests/mytest.cpp.o
.PHONY : tests/mytest.cpp.o

tests/mytest.i: tests/mytest.cpp.i

.PHONY : tests/mytest.i

# target to preprocess a source file
tests/mytest.cpp.i:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/tests/mytest.cpp.i
.PHONY : tests/mytest.cpp.i

tests/mytest.s: tests/mytest.cpp.s

.PHONY : tests/mytest.s

# target to generate assembly for a file
tests/mytest.cpp.s:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/tests/mytest.cpp.s
.PHONY : tests/mytest.cpp.s

tests/test_address.o: tests/test_address.cpp.o

.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cpp.o:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.o
.PHONY : tests/test_address.cpp.o

tests/test_address.i: tests/test_address.cpp.i

.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cpp.i:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.i
.PHONY : tests/test_address.cpp.i

tests/test_address.s: tests/test_address.cpp.s

.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cpp.s:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.s
.PHONY : tests/test_address.cpp.s

tests/test_bytearray.o: tests/test_bytearray.cpp.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cpp.o:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.o
.PHONY : tests/test_bytearray.cpp.o

tests/test_bytearray.i: tests/test_bytearray.cpp.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cpp.i:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.i
.PHONY : tests/test_bytearray.cpp.i

tests/test_bytearray.s: tests/test_bytearray.cpp.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cpp.s:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.s
.PHONY : tests/test_bytearray.cpp.s

tests/test_config.o: tests/test_config.cpp.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cpp.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.o
.PHONY : tests/test_config.cpp.o

tests/test_config.i: tests/test_config.cpp.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cpp.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.i
.PHONY : tests/test_config.cpp.i

tests/test_config.s: tests/test_config.cpp.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cpp.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.s
.PHONY : tests/test_config.cpp.s

tests/test_fiber.o: tests/test_fiber.cpp.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cpp.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.o
.PHONY : tests/test_fiber.cpp.o

tests/test_fiber.i: tests/test_fiber.cpp.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cpp.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.i
.PHONY : tests/test_fiber.cpp.i

tests/test_fiber.s: tests/test_fiber.cpp.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cpp.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.s
.PHONY : tests/test_fiber.cpp.s

tests/test_hook.o: tests/test_hook.cpp.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cpp.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.o
.PHONY : tests/test_hook.cpp.o

tests/test_hook.i: tests/test_hook.cpp.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cpp.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.i
.PHONY : tests/test_hook.cpp.i

tests/test_hook.s: tests/test_hook.cpp.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cpp.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.s
.PHONY : tests/test_hook.cpp.s

tests/test_http.o: tests/test_http.cpp.o

.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cpp.o:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.o
.PHONY : tests/test_http.cpp.o

tests/test_http.i: tests/test_http.cpp.i

.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cpp.i:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.i
.PHONY : tests/test_http.cpp.i

tests/test_http.s: tests/test_http.cpp.s

.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cpp.s:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.s
.PHONY : tests/test_http.cpp.s

tests/test_http_connection.o: tests/test_http_connection.cpp.o

.PHONY : tests/test_http_connection.o

# target to build an object file
tests/test_http_connection.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.o
.PHONY : tests/test_http_connection.cpp.o

tests/test_http_connection.i: tests/test_http_connection.cpp.i

.PHONY : tests/test_http_connection.i

# target to preprocess a source file
tests/test_http_connection.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.i
.PHONY : tests/test_http_connection.cpp.i

tests/test_http_connection.s: tests/test_http_connection.cpp.s

.PHONY : tests/test_http_connection.s

# target to generate assembly for a file
tests/test_http_connection.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.s
.PHONY : tests/test_http_connection.cpp.s

tests/test_http_parser.o: tests/test_http_parser.cpp.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.o
.PHONY : tests/test_http_parser.cpp.o

tests/test_http_parser.i: tests/test_http_parser.cpp.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.i
.PHONY : tests/test_http_parser.cpp.i

tests/test_http_parser.s: tests/test_http_parser.cpp.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.s
.PHONY : tests/test_http_parser.cpp.s

tests/test_http_server.o: tests/test_http_server.cpp.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.o
.PHONY : tests/test_http_server.cpp.o

tests/test_http_server.i: tests/test_http_server.cpp.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.i
.PHONY : tests/test_http_server.cpp.i

tests/test_http_server.s: tests/test_http_server.cpp.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.s
.PHONY : tests/test_http_server.cpp.s

tests/test_iomanager.o: tests/test_iomanager.cpp.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.o
.PHONY : tests/test_iomanager.cpp.o

tests/test_iomanager.i: tests/test_iomanager.cpp.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.i
.PHONY : tests/test_iomanager.cpp.i

tests/test_iomanager.s: tests/test_iomanager.cpp.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.s
.PHONY : tests/test_iomanager.cpp.s

tests/test_scheduler.o: tests/test_scheduler.cpp.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.o
.PHONY : tests/test_scheduler.cpp.o

tests/test_scheduler.i: tests/test_scheduler.cpp.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.i
.PHONY : tests/test_scheduler.cpp.i

tests/test_scheduler.s: tests/test_scheduler.cpp.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.s
.PHONY : tests/test_scheduler.cpp.s

tests/test_socket.o: tests/test_socket.cpp.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cpp.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.o
.PHONY : tests/test_socket.cpp.o

tests/test_socket.i: tests/test_socket.cpp.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cpp.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.i
.PHONY : tests/test_socket.cpp.i

tests/test_socket.s: tests/test_socket.cpp.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cpp.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.s
.PHONY : tests/test_socket.cpp.s

tests/test_tcpserver.o: tests/test_tcpserver.cpp.o

.PHONY : tests/test_tcpserver.o

# target to build an object file
tests/test_tcpserver.cpp.o:
	$(MAKE) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/tests/test_tcpserver.cpp.o
.PHONY : tests/test_tcpserver.cpp.o

tests/test_tcpserver.i: tests/test_tcpserver.cpp.i

.PHONY : tests/test_tcpserver.i

# target to preprocess a source file
tests/test_tcpserver.cpp.i:
	$(MAKE) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/tests/test_tcpserver.cpp.i
.PHONY : tests/test_tcpserver.cpp.i

tests/test_tcpserver.s: tests/test_tcpserver.cpp.s

.PHONY : tests/test_tcpserver.s

# target to generate assembly for a file
tests/test_tcpserver.cpp.s:
	$(MAKE) -f CMakeFiles/test_tcpserver.dir/build.make CMakeFiles/test_tcpserver.dir/tests/test_tcpserver.cpp.s
.PHONY : tests/test_tcpserver.cpp.s

tests/test_thread.o: tests/test_thread.cpp.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cpp.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.o
.PHONY : tests/test_thread.cpp.o

tests/test_thread.i: tests/test_thread.cpp.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cpp.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.i
.PHONY : tests/test_thread.cpp.i

tests/test_thread.s: tests/test_thread.cpp.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cpp.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.s
.PHONY : tests/test_thread.cpp.s

tests/test_uri.o: tests/test_uri.cpp.o

.PHONY : tests/test_uri.o

# target to build an object file
tests/test_uri.cpp.o:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.o
.PHONY : tests/test_uri.cpp.o

tests/test_uri.i: tests/test_uri.cpp.i

.PHONY : tests/test_uri.i

# target to preprocess a source file
tests/test_uri.cpp.i:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.i
.PHONY : tests/test_uri.cpp.i

tests/test_uri.s: tests/test_uri.cpp.s

.PHONY : tests/test_uri.s

# target to generate assembly for a file
tests/test_uri.cpp.s:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.s
.PHONY : tests/test_uri.cpp.s

tests/test_utils.o: tests/test_utils.cpp.o

.PHONY : tests/test_utils.o

# target to build an object file
tests/test_utils.cpp.o:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/tests/test_utils.cpp.o
.PHONY : tests/test_utils.cpp.o

tests/test_utils.i: tests/test_utils.cpp.i

.PHONY : tests/test_utils.i

# target to preprocess a source file
tests/test_utils.cpp.i:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/tests/test_utils.cpp.i
.PHONY : tests/test_utils.cpp.i

tests/test_utils.s: tests/test_utils.cpp.s

.PHONY : tests/test_utils.s

# target to generate assembly for a file
tests/test_utils.cpp.s:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/tests/test_utils.cpp.s
.PHONY : tests/test_utils.cpp.s

thread.o: thread.cpp.o

.PHONY : thread.o

# target to build an object file
thread.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/thread.cpp.o
.PHONY : thread.cpp.o

thread.i: thread.cpp.i

.PHONY : thread.i

# target to preprocess a source file
thread.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/thread.cpp.i
.PHONY : thread.cpp.i

thread.s: thread.cpp.s

.PHONY : thread.s

# target to generate assembly for a file
thread.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/thread.cpp.s
.PHONY : thread.cpp.s

timer.o: timer.cpp.o

.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i

.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/timer.cpp.s
.PHONY : timer.cpp.s

uri_rl.o: uri_rl.cpp.o

.PHONY : uri_rl.o

# target to build an object file
uri_rl.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/uri_rl.cpp.o
.PHONY : uri_rl.cpp.o

uri_rl.i: uri_rl.cpp.i

.PHONY : uri_rl.i

# target to preprocess a source file
uri_rl.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/uri_rl.cpp.i
.PHONY : uri_rl.cpp.i

uri_rl.s: uri_rl.cpp.s

.PHONY : uri_rl.s

# target to generate assembly for a file
uri_rl.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/uri_rl.cpp.s
.PHONY : uri_rl.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_uri"
	@echo "... test_http_connection"
	@echo "... test_http_server"
	@echo "... test_fiber"
	@echo "... test_socket"
	@echo "... test_iomanager"
	@echo "... test_thread"
	@echo "... test_bytearray"
	@echo "... test_config"
	@echo "... test_utils"
	@echo "... server"
	@echo "... test_scheduler"
	@echo "... test_hook"
	@echo "... test_address"
	@echo "... test_server"
	@echo "... test_http"
	@echo "... test_http_parser"
	@echo "... test_tcpserver"
	@echo "... echo_server"
	@echo "... address.o"
	@echo "... address.i"
	@echo "... address.s"
	@echo "... bytearray.o"
	@echo "... bytearray.i"
	@echo "... bytearray.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... example/echo_server.o"
	@echo "... example/echo_server.i"
	@echo "... example/echo_server.s"
	@echo "... fd_manager.o"
	@echo "... fd_manager.i"
	@echo "... fd_manager.s"
	@echo "... fiber.o"
	@echo "... fiber.i"
	@echo "... fiber.s"
	@echo "... hook.o"
	@echo "... hook.i"
	@echo "... hook.s"
	@echo "... http/http.o"
	@echo "... http/http.i"
	@echo "... http/http.s"
	@echo "... http/http11_parser_rl.o"
	@echo "... http/http11_parser_rl.i"
	@echo "... http/http11_parser_rl.s"
	@echo "... http/http_connection.o"
	@echo "... http/http_connection.i"
	@echo "... http/http_connection.s"
	@echo "... http/http_parser.o"
	@echo "... http/http_parser.i"
	@echo "... http/http_parser.s"
	@echo "... http/http_server.o"
	@echo "... http/http_server.i"
	@echo "... http/http_server.s"
	@echo "... http/httpclient_parser_rl.o"
	@echo "... http/httpclient_parser_rl.i"
	@echo "... http/httpclient_parser_rl.s"
	@echo "... http/httpsession.o"
	@echo "... http/httpsession.i"
	@echo "... http/httpsession.s"
	@echo "... http/servlet.o"
	@echo "... http/servlet.i"
	@echo "... http/servlet.s"
	@echo "... iomanager.o"
	@echo "... iomanager.i"
	@echo "... iomanager.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... scheduler.o"
	@echo "... scheduler.i"
	@echo "... scheduler.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
	@echo "... socketstream.o"
	@echo "... socketstream.i"
	@echo "... socketstream.s"
	@echo "... stream.o"
	@echo "... stream.i"
	@echo "... stream.s"
	@echo "... tcp_server.o"
	@echo "... tcp_server.i"
	@echo "... tcp_server.s"
	@echo "... tests/mytest.o"
	@echo "... tests/mytest.i"
	@echo "... tests/mytest.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_connection.o"
	@echo "... tests/test_http_connection.i"
	@echo "... tests/test_http_connection.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcpserver.o"
	@echo "... tests/test_tcpserver.i"
	@echo "... tests/test_tcpserver.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_uri.o"
	@echo "... tests/test_uri.i"
	@echo "... tests/test_uri.s"
	@echo "... tests/test_utils.o"
	@echo "... tests/test_utils.i"
	@echo "... tests/test_utils.s"
	@echo "... thread.o"
	@echo "... thread.i"
	@echo "... thread.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... uri_rl.o"
	@echo "... uri_rl.i"
	@echo "... uri_rl.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

